#!/usr/bin/env bash

set -e # automatically exit script on error

function showHelp() {
  echo "
        ydownloader is a script responsible
        for downloading SAP Hybris Commerce Suite from Artifactory
        and showing its download URL

        Usage:
          -d    downloading Commerce Suite
          -u    showing Commerce Suite Download Url
          -h    showing help
        "
}

function setCommerceSuiteVersion() {
  echo -n "SAP Hybris Commerce Suite version (leave empty for the latest): "
  read COMMERCE_SUITE_VERSION
}

function setArtifactType() {
  echo -n "Set artifact type (release or snapshot - leave empty for release): "
  read ARTIFACT_TYPE

  if [ "$ARTIFACT_TYPE" == "" ]
  then
    ARTIFACT_TYPE="release"
  fi
}

function setUsernameAndPassword() {
  echo -n "SAP username (e-mail): "
  read USERNAME
  echo -n "SAP password: "
  read -s PASSWORD
}

function setCommerceSuiteDownloadUrl() {
  setCommerceSuiteVersion
  setArtifactType
  setUsernameAndPassword

  echo $'\ngetting Commerce Suite download url from Artifactory...'

  setDownloadEndpoint
  setDownloadZipFileUrl
}

# get first endpoint for downloading Commerce Suite through Artifactory REST API
function setDownloadEndpoint() {
  setResponseWithUrlEndpoint
  parseResponseUrlWithEndpoint
}

function setResponseWithUrlEndpoint() {
  RESPONSE_WITH_URL_ENDPOINT=$(curl -s -u $USERNAME:$PASSWORD \
  https://repository.hybris.com/api/search/artifact\?name\=commerce-suite-$COMMERCE_SUITE_VERSION\&repos\=hybris-$ARTIFACT_TYPE)
}

function parseResponseUrlWithEndpoint() {
  COMMERCE_SUITE_DOWNLOAD_URL_ENDPOINT=`echo $RESPONSE_WITH_URL_ENDPOINT \
  | python -mjson.tool | grep zip | tail -1 | awk '{print $2}' | sed -e 's/^"//' -e 's/"$//'`
}

# get exact url of Commerce Suite from previously extracted endpoint
function setDownloadZipFileUrl() {
  setResponseWithUrlWithZipFile
  parseResponseUrlWithZipFile
}

function setResponseWithUrlWithZipFile() {
  RESPONSE_URL_WITH_ZIP_FILE=$(curl -s -u $USERNAME:$PASSWORD $COMMERCE_SUITE_DOWNLOAD_URL_ENDPOINT)
}

function parseResponseUrlWithZipFile() {
  COMMERCE_SUITE_URL_ZIP_FILE=`echo $RESPONSE_URL_WITH_ZIP_FILE \
  | python -mjson.tool | grep downloadUri | tail -1 | awk '{print $2}' | sed -e 's/^"//' -e 's/"$//' | rev | cut -c 3- | rev`
}

function showCommerceSuiteDownloadUrl() {
  setCommerceSuiteDownloadUrl
  echo $COMMERCE_SUITE_URL_ZIP_FILE
}

function downloadCommerceSuite() {
  setCommerceSuiteDownloadUrl
  echo $'\nstarting download of Commerce Suite from Artifactory...'
  wget --http-user=$USERNAME --http-password=$PASSWORD $COMMERCE_SUITE_URL_ZIP_FILE
}

OPTIND=1 # Reset in case getopts has been used previously in the shell.

while getopts "hud" opt; do
    case "$opt" in
    h)
        showHelp
        exit 0
        ;;
    u)  showCommerceSuiteDownloadUrl
        ;;
    d)  downloadCommerceSuite
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift
