#!/usr/bin/env bash

set -e # automatically exit script on error

function showHelp() {
  echo "
        ydownloader is a script responsible
        for downloading SAP Hybris Commerce Suite from Artifactory
        and showing its download URL

        Usage:
          -d    downloading Commerce Suite
          -u    showing Commerce Suite Download Url
          -h    showing help
        "
}

function setCommerceSuiteVersion() {
  echo -n "SAP Hybris Commerce Suite version (leave empty for the latest): "
  read -s COMMERCE_SUITE_VERSION
  echo ""
}

function setArtifactType() {
  echo -n "Set artifact type (release or snapshot - leave empty for release): "
  read -s ARTIFACT_TYPE

  if [ "$ARTIFACT_TYPE" == "" ]
  then
    ARTIFACT_TYPE="release"
  fi
  echo ""
}

function setUsernameAndPassword() {
  echo -n "SAP username (e-mail): "
  read USERNAME
  echo -n "SAP password: "
  read -s PASSWORD
}

function setCommerceSuiteDownloadUrl {
  setCommerceSuiteVersion
  setArtifactType
  setUsernameAndPassword

  echo $'\ngetting Commerce Suite download url from Artifactory...'

  # get first endpoint for downloading Commerce Suite through Artifactory REST API
  COMMERCE_SUITE_DOWNLOAD_URL_PREPARATION=`curl -s -u $USERNAME:$PASSWORD \
  https://repository.hybris.com/api/search/artifact\?name\=commerce-suite-$COMMERCE_SUITE_VERSION\&repos\=hybris-$ARTIFACT_TYPE \
  | python -mjson.tool | grep zip | tail -1 | awk '{print $2}' | sed -e 's/^"//' -e 's/"$//'`

  # get exact url of Commerce Suite from previously extracted endpoint
  COMMERCE_SUITE_DOWNLOAD_URL=`curl -s -u $USERNAME:$PASSWORD $COMMERCE_SUITE_DOWNLOAD_URL_PREPARATION \
  | python -mjson.tool | grep downloadUri | tail -1 | awk '{print $2}' | sed -e 's/^"//' -e 's/"$//' | rev | cut -c 3- | rev`
}

function showCommerceSuiteDownloadUrl() {
  setCommerceSuiteDownloadUrl
  echo $COMMERCE_SUITE_DOWNLOAD_URL
}

function downloadCommerceSuite() {
  setCommerceSuiteDownloadUrl
  wget --http-user=$USERNAME --http-password=$PASSWORD $COMMERCE_SUITE_DOWNLOAD_URL

}

OPTIND=1 # Reset in case getopts has been used previously in the shell.

while getopts "hud" opt; do
    case "$opt" in
    h)
        showHelp
        exit 0
        ;;
    u)  showCommerceSuiteDownloadUrl
        ;;
    d)  downloadCommerceSuite
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift
